### ISSUE TITLE
Zugriff auf GitHub und Project ersteilen

### ISSUE THREAD

**Issue by michschl** [swissfintechinnovations/ca-security#1]
michael.staehli@synpulse.com / MichaelStaehli
remo@schlauri.net / rschlauri
jay.padiyath@gmx.ch
sebastian.hagen@ubs.com
eric.mueller@postfinance.ch / muellereri

**Comment by mibrand** [comment]
Kann keine Members hinzufügen. Die müssen wohl erst auf der Organisation erfasst werden, so dass ich sie nachher dem Projekt zuweisen kann. Hast du diese Rechte, oder kannst du sie mir geben, damit ich die neuen Members erfassen kann?

**Comment by michschl** [comment]
Stimmt, kannst du eine Liste zusammenstellen und an Dominik König schicken? Der kann die hinzufügen.Lg MichiVon meinem iPhone gesendetAm 05.06.2024 um 11:48 schrieb mibrand ***@***.***>:﻿
Kann keine Members hinzufügen. Die müssen wohl erst auf der Organisation erfasst werden, so dass ich sie nachher dem Projekt zuweisen kann.

**Comment by mibrand** [comment]
Hoi MichiMache ich gerne!LG MischaVon meinem iPhone gesendetAm 05.06.2024 um 16:06 schrieb michschl ***@***.***>:﻿
Stimmt, kannst du eine Liste zusammenstellen und an Dominik König schicken? Der kann die hinzufügen.Lg MichiVon meinem iPhone gesendetAm 05.06.2024 um 11:48 schrieb mibrand ***@***.***>:﻿

Kann keine Members hinzufügen. Die müssen wohl erst auf der Organisation erfasst werden, so dass ich sie nachher dem Projekt zuweisen kann.

**Comment by dkoeni** [comment]
Invited.
